### ISSUE TITLE
Readme should include screenshot example

### ISSUE THREAD

**Issue by ZevEisenberg** [cashapp/AccessibilitySnapshot#126]
Someone told me about this library, and they sent me a screenshot of some example usage, and it told a super compelling story. Classic "a picture is worth a thousand words" stuff. I think if the readme had a sample screenshot at the top, it would make the use of this repo a lot easier to understand.

**Comment by ZevEisenberg** [comment]
I found a bunch of examples in https://github.com/cashapp/AccessibilitySnapshot/tree/master/Example/SnapshotTests/__Snapshots__/SnapshotTestingTests that you could probably use as-is, or it might be clever to craft something a little more illustrative.

**Comment by NickEntin** [comment]
Thanks Zev, that's a great idea! Do you have one example in mind you think would stand out? What about using the example from the [blog post announcing the framework](https://code.cash.app/making-ios-accessibility-testing-easy)?

**Comment by ZevEisenberg** [comment]
That's a good one! Although for some reason, I was thinking that side-by-side would be more compelling. Something like [this](
![](https://github.com/cashapp/AccessibilitySnapshot/blob/master/Example/SnapshotTests/__Snapshots__/SnapshotTestingTests/testShowingActivationPoint.whenOverridden-375x812-13-7-3x.png)
), but maybe smaller and with a few more controls.

But I think the one in the blog post is better than nothing.

**Comment by NickEntin** [comment]
I updated the README to include the sample snapshot from the blog post for now. I'm going to be going some more work on the documentation, so if I come up with a better example as part of that I'll update the README again.

**Comment by ZevEisenberg** [comment]
It looks great!
