### ISSUE TITLE
Using `imageWithSmartInvert` with  `isRecording = true/false` - fails everytime

### ISSUE THREAD

**Issue by parikhparth23** [cashapp/AccessibilitySnapshot#127]
I am using the `imageWithSmartInvert` with `isRecording = true/false` and the test always fails

`assertSnapshot(matching: view, as: .imageWithSmartInvert)`

My original image is:
![original](https://user-images.githubusercontent.com/10181201/235813639-cad40aa9-78d3-49f4-8ef6-5de85b549808.png)

when i run with `isRecording=true` it generated the Black/Golden image.
when i run it with `isRecording=false` the snapshot does not match reference. 

```
.
.
.
failed - Snapshot does not match reference.

"/Users/abc/Library/Developer/CoreSimulator/Devices/ACC40F6C-1421-4D1B-9008-20C0EB7B81EE/data/Containers/Bundle/Application/14408B86-E69D-4390-9E8D-0A050D98F518/SmallAppHost.app/PlugIns/SnapshotTests.xctest/SnapshotTestsBundle.bundle/Snapshots/Tests/testLoading.1.png"
@+
"/Users/abc/Library/Developer/CoreSimulator/Devices/ACC40F6C-1421-4D1B-9008-20C0EB7B81EE/data/Containers/Data/Application/E4FA0EDE-9A8C-4B4A-9E7B-4FDDBDF81EDB/tmp/Tests/testLoading.1.png"

Newly-taken snapshot does not match reference.
.
.
.
```

i tried opening the image in above locations - both are same -
![1](https://user-images.githubusercontent.com/10181201/235813156-aa43f188-b7c2-4c7d-a444-05ff302be146.png)
![2](https://user-images.githubusercontent.com/10181201/235813159-a343456f-2370-4cc0-a06e-3080805bab11.png)

can you please have a look?

**Comment by parikhparth23** [comment]
attaching the images from xcresult:
![difference_3_75227A15-33D8-4D2B-9FCA-46C3B457D1A5](https://user-images.githubusercontent.com/10181201/236016107-d3fdf73e-f2ed-4c93-b70e-726e9cb051eb.png)
![failure_2_75227A15-33D8-4D2B-9FCA-46C3B457D1A5](https://user-images.githubusercontent.com/10181201/236016112-889b3e8f-ed3c-4543-84dc-2f20927d9697.png)
![reference_1_75227A15-33D8-4D2B-9FCA-46C3B457D1A5](https://user-images.githubusercontent.com/10181201/236016115-ba941ef5-a4b3-40ac-af49-e744defc079f.png)


zoom into the centre of the `difference` image and you will see the difference

**Comment by parikhparth23** [comment]
the difference is 
![Screenshot 2023-05-03 at 11 52 14 AM](https://user-images.githubusercontent.com/10181201/236024287-22d27e2c-f035-4724-9dfd-9a15bff83ad5.png)

**Comment by NickEntin** [comment]
Hi Parth! Can you provide some more details about what you're snapshotting? Is that a simple `UIImageView` in the center of the screen? If you have a branch that reproduces the issue, that would greatly help me investigate what's going wrong.

**Comment by parikhparth23** [comment]
@NickEntin - i and @abinodhthomas have added a support to add the precision - https://github.com/parikhparth23/AccessibilitySnapshot
plz have a look and merge it.

**Comment by NickEntin** [comment]
If you're seeing this on subsequent runs on the same machine, it sounds like there's likely an underlying issue going on here. While adding precision might work around it, I'd like to see if we can figure out the root problem first. Can you provide a code sample that reproduces the issue?

**Comment by parikhparth23** [comment]
@NickEntin i wish i could share the code or even a snippet. the code is a proprietary code.
i tried creating a sample app and it works without any issue. 
do you mind merging the precision code to your repo? - if you do it i will be able to use this framework. And i will look into our code base why the image is failing.

**Comment by parikhparth23** [comment]
the precision value by default is to match 100%

**Comment by NickEntin** [comment]
There is now tolerance parameters available when using FBSnapshotTestCase as the snapshotting engine. Support for SnapshotTesting is tracked by #63.

That said, I would _highly_ recommend looking into why your views are not able to pass consecutive snapshots on the same machine and only use precision for inter-machine comparison failures. Perhaps you need to disable animations, or something along those lines? The framework is not designed to support snapshotting non-deterministic rendering views.
