### ISSUE TITLE
VoiceOver no longer states "actions available" for elements with custom actions

### ISSUE THREAD

**Issue by NickEntin** [cashapp/AccessibilitySnapshot#159]
In iOS 16, VoiceOver no longer states "actions available" for elements that have custom accessibility actions. We should remove this text from the legend.

**Comment by NickEntin** [comment]
Possible this changed in iOS 15. Need to verify through #67.

**Comment by RoyalPineapple** [comment]
This is configurable through Settings> Accessibility> VoiceOver> Verbosity> Actions. The default value still contains "Speak" which triggers the "Actions Available" announcement. 
![AccessibilityActions](https://github.com/cashapp/AccessibilitySnapshot/assets/219578/16354917-9602-4948-bbd6-ca60b361b896)

**Comment by NickEntin** [comment]
Ahhh I must have accidentally changed this. I'll go ahead and close out the ticket. Thanks!
