### ISSUE TITLE
Provide higher contrast marker labels for host applications set to dark mode

### ISSUE THREAD

**Issue by nononoah** [cashapp/AccessibilitySnapshot#174]
Warning: I have not yet verified if this is reproducible outside of my test application.

When testing in host applications with a user interface style of dark, it appears that accessibility snapshots produce rather low contrast marker labels.

In light mode:
![testVariants accessibility](https://github.com/cashapp/AccessibilitySnapshot/assets/1542313/65fdb7b3-139e-43da-b0ab-d84aa63d4f65)

In dark mode:
![testVariants accessibility](https://github.com/cashapp/AccessibilitySnapshot/assets/1542313/f962268b-88f9-4c38-8692-749cc206c44f)

Ideally, we'd use a text color which is better guaranteed to contrast.

**Comment by NickEntin** [comment]
Ahh good find! I always run test host applications in light mode, so totally missed it was defaulting to a dynamic color. Thanks for the bug report!
