### ISSUE TITLE
Add `IDETemplateMacro` to generate correct header in new files

### ISSUE THREAD

**Issue by fbernutz** [cashapp/AccessibilitySnapshot#53]
When creating a new file in Xcode the copyright text on top of the file will differentiate between the text in the other files. With adding a `IDETemplateMacros.plist` file this could be generated correctly and would help new contributors with this. The file could be added to the workspace of the example project: `<WorkspaceName>.xcworkspace/xcshareddata/IDETemplateMacros.plist`, so it would be shared across the workspace. 

I could try this out and add a PR for that, if you want. What do you think about that? 

(For more information about that, you can read this article: https://oleb.net/blog/2017/07/xcode-9-text-macros/ I think this is still the same way to go even if the post is already three years old.)

**Comment by NickEntin** [comment]
Oh awesome, didn't realize you could set that at a shared workplace level. A PR adding that would definitely be appreciated!
