### ISSUE TITLE
Do you want more Localizations?

### ISSUE THREAD

**Issue by fruitcoder** [cashapp/AccessibilitySnapshot#61]
Since I am running my tests in another language than English, the resulting snapshot is mixed-language. Should I add German to [Localizable.strings](https://github.com/cashapp/AccessibilitySnapshot/blob/master/Sources/AccessibilitySnapshot/Core/Swift/Assets/en.lproj/Localizable.strings) and if so how did you get the Strings for English? Just from experience or do you have a sample app that allows you to extract all the Strings from?

**Comment by NickEntin** [comment]
Thanks for your interest @fruitcoder! More localizations would be a great improvement to the framework.

All of the strings came from running the [demo app](https://github.com/cashapp/AccessibilitySnapshot/tree/cc470c70026fc77068a8a93fef414e70a482dcda/Example) with VoiceOver enabled and picking out the words/phrases that VoiceOver uses. For the most part you should be able to pair each screen in the demo app with a snapshot reference image and match the output from VoiceOver with the written description in the snapshots.

**Comment by fruitcoder** [comment]
Awesome! I'll try to create a PR this week 👍

**Comment by fruitcoder** [comment]
#62

**Comment by NickEntin** [comment]
I'm going to mark this issue as closed since we've merged in the German localization now. Support for other languages should probably be tracked by individual tickets.
