### ISSUE TITLE
Use  SnapshotTesting  instead of iOSSnapshotTestCase

### ISSUE THREAD

**Issue by barrault01** [cashapp/AccessibilitySnapshot#8]
It will be nice to support https://github.com/pointfreeco/swift-snapshot-testing for taking the screenshots it’s a 100% Swift library and it’s already have SPM support.

**Comment by Sherlouk** [comment]
This was raised in #3! You can now use https://github.com/Sherlouk/AccessibilitySnapshotPointfree if you wish to use this library with SnapshotTesting.
