### ISSUE TITLE
Update iOSSnapshotTestCase dependency

### ISSUE THREAD

**Issue by mattprowse-xero** [cashapp/AccessibilitySnapshot#96]
The iOSSnapshotTestCase dependency is currently set to `~> 6.0` but the latest available version is 8.0.0, which makes it impossible to incorporate AccessibilitySnapshot into projects that are already using the latest version of iOSsnapshotTestCase without downgrading. I'm very keen to incorporate AccessibilitySnapshot into a project I'm working on, but this is currently a blocker.

More than happy to submit a PR, though I noticed that there's an open PR (#72) for adding iOSsnapshotTestCase support via SPM, which might be a better place to make this change?

**Comment by NickEntin** [comment]
Thanks for your interest in the project! I opened #97 to get SPM support working again. I'll make sure to get it updated to the latest version of iOSSnapshotTestCase in that PR.
