### ISSUE TITLE
Migrate off of GitHub Actions macOS 10.15

### ISSUE THREAD

**Issue by NickEntin** [cashapp/AccessibilitySnapshot#98]
GitHub Actions has deprecated their 10.15 runners:

https://github.com/actions/runner-images/issues/5583

We have until the end of the month to migrate off.

**Comment by NickEntin** [comment]
Unfortunately the [macOS 11 images](https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md) don't include iOS 12 SDKs, which means we're going to lose our iOS 12 CI builds if we migrate to the macOS 11 image.

**Comment by NickEntin** [comment]
Marking this as a P0 because in about a week we'll lose our CI builds if we don't act on this right now.

**Comment by NickEntin** [comment]
Looks like this got [extended](https://github.com/actions/runner-images/pull/6167/files) to 12/1/22.

**Comment by eliperkins** [comment]
@NickEntin  👋  Is testing for iOS 12 a requirement for this project? If not, I'd be happy to lend a hand here to migrate to the macOS 11 runner and test on iOS 13.7, iOS 14.5 and iOS 15.2, which are all [included in the macOS 11 image](https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md#installed-sdks)!

If testing on iOS 12 is a requirement, do you know of some good ways that we could download the iOS 12 SDK/simulator runtime that doesn't involve hardcoding an iOS 12 runtime URL from `devimages.apple.com`? It looks like [`xcode-install` might support this](https://github.com/xcpretty/xcode-install/blob/5c8f23f49f85659a89210d333cbe145b1c6b44b1/lib/xcode/install.rb#L662-L666), but I'm not sure that bringing in a Ruby dependency here is how we might wanna fix it.

It seems like we could potentially [automate this with `xcrun simctl runtime add`](https://developer.apple.com/documentation/xcode/installing-additional-simulator-runtimes), but downloading a 5gb runtime on every Action run seems potentially slow. 😬

**Comment by NickEntin** [comment]
Hey @eliperkins! Apologies, missed your message... my GitHub notification queue has been a mess. 😅 

We're currently in the process of dropping iOS 12 support (just landed the bump for SPM in #106), so I think we're good to go on dropping the iOS 12 CI build. Do you still have bandwidth to help with this migration?
